/* eslint-disable */
/**
 * Generated by Convex — stub file for build compatibility.
 * This will be replaced when `npx convex dev` is run.
 */

import type { FunctionReference } from "convex/server";
import type { Doc, Id } from "./dataModel";

/**
 * Pagination types matching Convex's built-in pagination.
 */
interface PaginationOpts {
	numItems: number;
	cursor: string | null;
}

interface PaginationResult<T> {
	page: T[];
	isDone: boolean;
	continueCursor: string;
}

type GeneratedAPI = {
	bookmarkCollections: {
		add: FunctionReference<
			"mutation",
			"public",
			{ clerkId: string; bookmarkId: Id<"bookmarks">; collectionId: Id<"collections"> },
			Id<"bookmarkCollections">
		>;
		remove: FunctionReference<
			"mutation",
			"public",
			{ clerkId: string; bookmarkId: Id<"bookmarks">; collectionId: Id<"collections"> },
			Id<"bookmarkCollections">
		>;
		getByBookmark: FunctionReference<
			"query",
			"public",
			{ clerkId: string; bookmarkId: Id<"bookmarks"> },
			Doc<"collections">[]
		>;
	};
	bookmarks: {
		list: FunctionReference<
			"query",
			"public",
			{
				clerkId: string;
				isFavorite?: boolean;
				isArchived?: boolean;
				collectionId?: Id<"collections">;
				tag?: string;
				paginationOpts: PaginationOpts;
			},
			PaginationResult<Doc<"bookmarks">>
		>;
		get: FunctionReference<
			"query",
			"public",
			{ clerkId: string; bookmarkId: Id<"bookmarks"> },
			Doc<"bookmarks"> | null
		>;
		search: FunctionReference<
			"query",
			"public",
			{ clerkId: string; searchQuery: string },
			Doc<"bookmarks">[]
		>;
		getFavorites: FunctionReference<
			"query",
			"public",
			{ clerkId: string },
			Doc<"bookmarks">[]
		>;
		getRecent: FunctionReference<
			"query",
			"public",
			{ clerkId: string },
			Doc<"bookmarks">[]
		>;
		getStats: FunctionReference<
			"query",
			"public",
			{ clerkId: string },
			{ total: number; thisWeek: number; favorites: number; archived: number }
		>;
		create: FunctionReference<
			"mutation",
			"public",
			{
				clerkId: string;
				url: string;
				title: string;
				description?: string;
				thumbnailUrl?: string;
				siteName?: string;
				favicon?: string;
				tags?: string[];
			},
			Id<"bookmarks">
		>;
		update: FunctionReference<
			"mutation",
			"public",
			{
				clerkId: string;
				bookmarkId: Id<"bookmarks">;
				title?: string;
				description?: string;
				url?: string;
				thumbnailUrl?: string;
				siteName?: string;
				favicon?: string;
				aiSummary?: string;
				tags?: string[];
			},
			Id<"bookmarks">
		>;
		remove: FunctionReference<
			"mutation",
			"public",
			{ clerkId: string; bookmarkId: Id<"bookmarks"> },
			Id<"bookmarks">
		>;
		toggleFavorite: FunctionReference<
			"mutation",
			"public",
			{ clerkId: string; bookmarkId: Id<"bookmarks"> },
			boolean
		>;
		toggleArchive: FunctionReference<
			"mutation",
			"public",
			{ clerkId: string; bookmarkId: Id<"bookmarks"> },
			boolean
		>;
		incrementReadCount: FunctionReference<
			"mutation",
			"public",
			{ clerkId: string; bookmarkId: Id<"bookmarks"> },
			number
		>;
	};
	chatMessages: {
		list: FunctionReference<
			"query",
			"public",
			{ clerkId: string },
			Doc<"chatMessages">[]
		>;
		create: FunctionReference<
			"mutation",
			"public",
			{
				clerkId: string;
				role: "user" | "assistant";
				content: string;
				sources?: Id<"bookmarks">[];
			},
			Id<"chatMessages">
		>;
		clear: FunctionReference<
			"mutation",
			"public",
			{ clerkId: string },
			number
		>;
	};
	collections: {
		list: FunctionReference<
			"query",
			"public",
			{ clerkId: string },
			Doc<"collections">[]
		>;
		get: FunctionReference<
			"query",
			"public",
			{ clerkId: string; collectionId: Id<"collections"> },
			Doc<"collections"> | null
		>;
		getBookmarks: FunctionReference<
			"query",
			"public",
			{ clerkId: string; collectionId: Id<"collections"> },
			Doc<"bookmarks">[]
		>;
		create: FunctionReference<
			"mutation",
			"public",
			{
				clerkId: string;
				name: string;
				description?: string;
				icon?: string;
				color?: string;
			},
			Id<"collections">
		>;
		update: FunctionReference<
			"mutation",
			"public",
			{
				clerkId: string;
				collectionId: Id<"collections">;
				name?: string;
				description?: string;
				icon?: string;
				color?: string;
			},
			Id<"collections">
		>;
		remove: FunctionReference<
			"mutation",
			"public",
			{ clerkId: string; collectionId: Id<"collections"> },
			Id<"collections">
		>;
	};
	notes: {
		getByBookmark: FunctionReference<
			"query",
			"public",
			{ clerkId: string; bookmarkId: Id<"bookmarks"> },
			Doc<"notes">[]
		>;
		create: FunctionReference<
			"mutation",
			"public",
			{ clerkId: string; bookmarkId: Id<"bookmarks">; content: string },
			Id<"notes">
		>;
		update: FunctionReference<
			"mutation",
			"public",
			{ clerkId: string; noteId: Id<"notes">; content: string },
			Id<"notes">
		>;
		remove: FunctionReference<
			"mutation",
			"public",
			{ clerkId: string; noteId: Id<"notes"> },
			Id<"notes">
		>;
	};
	users: {
		createOrUpdate: FunctionReference<
			"mutation",
			"public",
			{
				clerkId: string;
				name: string;
				email: string;
				imageUrl?: string;
			},
			Id<"users">
		>;
		getCurrent: FunctionReference<
			"query",
			"public",
			{ clerkId: string },
			Doc<"users"> | null
		>;
	};
};

export const api = {} as unknown as GeneratedAPI;
export const internal = {} as unknown as Record<
	string,
	Record<string, FunctionReference<"query" | "mutation" | "action">>
>;
