/* eslint-disable */
/**
 * Generated by Convex — stub file for build compatibility.
 * This will be replaced when `npx convex dev` is run.
 */

import type { GenericId } from "convex/values";

export type Id<TableName extends string> = GenericId<TableName>;

/**
 * Typed document definitions matching convex/schema.ts.
 * These stubs provide compile-time safety until real codegen runs.
 */
interface DocTypes {
	users: {
		_id: Id<"users">;
		_creationTime: number;
		clerkId: string;
		name: string;
		email: string;
		imageUrl?: string;
		plan: "free" | "pro";
		bookmarkCount: number;
		createdAt: number;
	};
	bookmarks: {
		_id: Id<"bookmarks">;
		_creationTime: number;
		userId: Id<"users">;
		url: string;
		title: string;
		description?: string;
		thumbnailUrl?: string;
		siteName?: string;
		favicon?: string;
		aiSummary?: string;
		tags: string[];
		isFavorite: boolean;
		isArchived: boolean;
		readCount: number;
		lastReadAt?: number;
		createdAt: number;
		updatedAt: number;
	};
	collections: {
		_id: Id<"collections">;
		_creationTime: number;
		userId: Id<"users">;
		name: string;
		description?: string;
		icon?: string;
		color?: string;
		bookmarkCount: number;
		createdAt: number;
		updatedAt: number;
	};
	bookmarkCollections: {
		_id: Id<"bookmarkCollections">;
		_creationTime: number;
		bookmarkId: Id<"bookmarks">;
		collectionId: Id<"collections">;
		userId: Id<"users">;
		addedAt: number;
	};
	chatMessages: {
		_id: Id<"chatMessages">;
		_creationTime: number;
		userId: Id<"users">;
		role: "user" | "assistant";
		content: string;
		sources?: Id<"bookmarks">[];
		createdAt: number;
	};
	notes: {
		_id: Id<"notes">;
		_creationTime: number;
		userId: Id<"users">;
		bookmarkId: Id<"bookmarks">;
		content: string;
		createdAt: number;
		updatedAt: number;
	};
}

export type Doc<TableName extends string> = TableName extends keyof DocTypes
	? DocTypes[TableName]
	: { _id: Id<TableName>; _creationTime: number; [key: string]: unknown };

export type DataModel = {
	[K in keyof DocTypes]: {
		document: DocTypes[K];
		fieldPaths: string;
		indexes: Record<string, string>;
		searchIndexes: Record<string, string>;
		vectorIndexes: Record<string, string>;
	};
};
